-- seed.sql
-- Deterministic sample data. Uses fixed UUIDs so rows can reference each other readably.
-- Run after all migrations (001-009). firm_url is intentionally NOT supplied — the
-- generate_firm_url trigger fills it. Counters are left at their defaults and are driven up by
-- the like/comment triggers as the engagement rows below are inserted.

BEGIN;

-- ---- users --------------------------------------------------------------------------------
INSERT INTO users (id, email, name, current_title, current_company, bio,
                   location_city, location_state, location_country, location_longitude, location_latitude)
VALUES
 ('a0000000-0000-0000-0000-000000000001', 'alice@example.com',  'Alice Nguyen',   'Equity Analyst',        'Vanguard Advisors', 'Covering financials.',  'New York',  'NY', 'USA', -73.9857, 40.7484),
 ('a0000000-0000-0000-0000-000000000002', 'bob@example.com',    'Bob Martinez',   'Portfolio Manager',     'Vanguard Advisors', 'Long-term value.',      'New York',  'NY', 'USA', -73.9680, 40.7851),
 ('a0000000-0000-0000-0000-000000000003', 'carol@example.com',  'Carol Smith',    'Head of Research',      'Summit Capital',    'Macro + crypto.',       'San Francisco','CA','USA', -122.4194, 37.7749),
 ('a0000000-0000-0000-0000-000000000004', 'dave@example.com',   'Dave Okafor',    'Quant Developer',       'Meridian Wealth',   'Factors and data.',     'Chicago',   'IL', 'USA', -87.6298, 41.8781),
 ('a0000000-0000-0000-0000-000000000005', 'erin@example.com',   'Erin Walsh',     'Financial Advisor',     'Meridian Wealth',   'Retirement planning.',  'London',    NULL, 'UK',  -0.1276, 51.5072),
 ('a0000000-0000-0000-0000-000000000006', 'frank@example.com',  'Frank Li',       'Risk Manager',          'Summit Capital',    'Tail risk.',            'New York',  'NY', 'USA', -73.9772, 40.7527),
 ('a0000000-0000-0000-0000-000000000007', 'grace@example.com',  'Grace Adeyemi',  'Investment Banking VP', 'Vanguard Advisors', 'M&A.',                  'Chicago',   'IL', 'USA', -87.6244, 41.8819),
 ('a0000000-0000-0000-0000-000000000008', 'heidi@example.com',  'Heidi Brenner',  'Compliance Officer',    'Meridian Wealth',   'Reg and controls.',     'London',    NULL, 'UK',  -0.1180, 51.5099);

-- ---- organizations (firm_url auto-generated by trigger) -----------------------------------
INSERT INTO organizations (id, name, description, overview, size, categories,
                           location_city, location_state, location_country, location_longitude, location_latitude)
VALUES
 ('b0000000-0000-0000-0000-000000000001', 'Vanguard Advisors', 'Boutique equity research.', 'Independent equity research and advisory.', '11-50',  ARRAY['research','advisory'],       'New York','NY','USA', -73.9857, 40.7484),
 ('b0000000-0000-0000-0000-000000000002', 'Summit Capital',    'Global macro fund.',        'Discretionary global macro and digital assets.', '51-200', ARRAY['hedge-fund','macro','crypto'], 'San Francisco','CA','USA', -122.4194, 37.7749),
 ('b0000000-0000-0000-0000-000000000003', 'Meridian Wealth',   'Wealth management.',        'Retirement and wealth planning for professionals.', '201-500', ARRAY['wealth','advisory'],       'Chicago','IL','USA', -87.6298, 41.8781);

-- ---- firm membership ----------------------------------------------------------------------
INSERT INTO organization_members (organization_id, user_id, role) VALUES
 ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'owner'),
 ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', 'member'),
 ('b0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', 'owner'),
 ('b0000000-0000-0000-0000-000000000003', 'a0000000-0000-0000-0000-000000000004', 'member');

-- ---- user connections ---------------------------------------------------------------------
INSERT INTO user_connections (requester_id, target_id, status, personal_note) VALUES
 ('a0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', 'accepted', 'Great to connect!'),
 ('a0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000003', 'pending',  'Enjoyed your macro note.'),
 ('a0000000-0000-0000-0000-000000000004', 'a0000000-0000-0000-0000-000000000005', 'accepted', NULL),
 ('a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', 'rejected', NULL),
 ('a0000000-0000-0000-0000-000000000007', 'a0000000-0000-0000-0000-000000000001', 'pending',  'Fellow VA colleague.');

-- ---- follows ------------------------------------------------------------------------------
INSERT INTO organization_follows (user_id, organization_id) VALUES
 ('a0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000002'),
 ('a0000000-0000-0000-0000-000000000004', 'b0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000005', 'b0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000006', 'b0000000-0000-0000-0000-000000000002');

-- ---- firm member requests -----------------------------------------------------------------
INSERT INTO firm_member_requests (user_id, organization_id, status, personal_note) VALUES
 ('a0000000-0000-0000-0000-000000000004', 'b0000000-0000-0000-0000-000000000001', 'pending', 'Would love to join VA.'),
 ('a0000000-0000-0000-0000-000000000006', 'b0000000-0000-0000-0000-000000000002', 'accepted', NULL);

-- ---- posts (body text notionally in TurboPuffer; only metadata here) ----------------------
INSERT INTO posts (id, author_id, firm_id, hashtags) VALUES
 ('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', NULL,                                      ARRAY['finance','markets']),
 ('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000001',    ARRAY['equities']),  -- posted as the firm
 ('c0000000-0000-0000-0000-000000000003', 'a0000000-0000-0000-0000-000000000003', NULL,                                      ARRAY['crypto','markets']),
 ('c0000000-0000-0000-0000-000000000005', 'a0000000-0000-0000-0000-000000000004', NULL,                                      ARRAY['finance']);

-- a repost: post 4 shares post 3
INSERT INTO posts (id, author_id, firm_id, hashtags, shared_post_id) VALUES
 ('c0000000-0000-0000-0000-000000000004', 'a0000000-0000-0000-0000-000000000001', NULL, ARRAY[]::text[], 'c0000000-0000-0000-0000-000000000003');

-- ---- articles -----------------------------------------------------------------------------
INSERT INTO articles (id, author_id, firm_id, cover_image) VALUES
 ('d0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', NULL,                                   'https://img.example.com/a1.png'),
 ('d0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', 'b0000000-0000-0000-0000-000000000002', 'https://img.example.com/a2.png');

-- ---- comments (replies) -------------------------------------------------------------------
INSERT INTO comments (id, author_id, post_id, body) VALUES
 ('e0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001', 'Solid take, Alice.'),
 ('e0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000001', 'Curious about the downside case.');
INSERT INTO comments (id, author_id, article_id, body) VALUES
 ('e0000000-0000-0000-0000-000000000003', 'a0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000002', 'Great long-form piece.');

-- ---- likes (post/article + a couple of reply-likes) ---------------------------------------
INSERT INTO likes (user_id, post_id) VALUES
 ('a0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000004', 'c0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000003');
INSERT INTO likes (user_id, article_id) VALUES
 ('a0000000-0000-0000-0000-000000000005', 'd0000000-0000-0000-0000-000000000001');
-- reply-likes: two users like comment e...01
INSERT INTO likes (user_id, comment_id) VALUES
 ('a0000000-0000-0000-0000-000000000004', 'e0000000-0000-0000-0000-000000000001'),
 ('a0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001');

COMMIT;

-- After load, expected counters (driven by triggers):
--   post   c...01: like_count=3, comment_count=2
--   post   c...03: like_count=1
--   article d...01: like_count=1
--   comment e...01: like_count=2
